# Auto-label PRs based on file changes
# Format for actions/labeler@v5

enhancement:
  - any: ['src/**/*.ts', 'src/**/*.tsx']
    all: ['!src/**/*.test.ts', '!src/**/*.spec.ts']

bug:
  - any: ['src/**/*.ts', 'src/**/*.tsx']
    all: ['!src/**/*.test.ts', '!src/**/*.spec.ts']

documentation:
  - any: ['*.md', 'docs/**', 'README*.md', 'CONTRIBUTING.md', '.github/**/*.md', 'wiki/**']

dependencies:
  - any: ['package.json', 'package-lock.json', 'yarn.lock', 'pnpm-lock.yaml']

'github-actions':
  - any: ['.github/workflows/**', '.github/actions/**']

testing:
  - any: ['**/*.test.ts', '**/*.test.tsx', '**/*.spec.ts', '**/*.spec.tsx', 'jest.config.*', 'vitest.config.*']

prisma:
  - any: ['prisma/**']

api:
  - any: ['src/app/api/**']

components:
  - any: ['src/components/**']

lib:
  - any: ['src/lib/**']

