# Auto-label PRs based on file changes

'enhancement':
  - 'src/**/*.ts'
  - 'src/**/*.tsx'
  - '!src/**/*.test.ts'
  - '!src/**/*.spec.ts'

'bug':
  - 'src/**/*.ts'
  - 'src/**/*.tsx'
  - '!src/**/*.test.ts'
  - '!src/**/*.spec.ts'

'documentation':
  - '*.md'
  - 'docs/**'
  - 'README*.md'
  - 'CONTRIBUTING.md'
  - '.github/**/*.md'

'dependencies':
  - 'package.json'
  - 'package-lock.json'
  - 'yarn.lock'
  - 'pnpm-lock.yaml'

'github-actions':
  - '.github/workflows/**'
  - '.github/actions/**'

'testing':
  - '**/*.test.ts'
  - '**/*.test.tsx'
  - '**/*.spec.ts'
  - '**/*.spec.tsx'
  - 'jest.config.*'
  - 'vitest.config.*'

'prisma':
  - 'prisma/**'

'api':
  - 'src/app/api/**'

'components':
  - 'src/components/**'

'lib':
  - 'src/lib/**'

